app:
  build: .
  ports:
    - 1337:1337
  command: gulp.js $TASK
  volumes:
    - ".:/app"
  environment:
    - PATH=$PATH:/usr/local/nvm/versions/node/v5.5.0/bin/:/app/node_modules/gulp/bin/
    - APP_PORT=1337
    - APP_ENV=development
